// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OTELREHBER.DataBaseContext;

#nullable disable

namespace OTELREHBER.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OTELREHBER.Entitiy.Otel", b =>
                {
                    b.Property<long>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UUID"));

                    b.Property<string>("FirmaUnvan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YekiliSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YetkiliAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UUID");

                    b.ToTable("Otels");
                });

            modelBuilder.Entity("OTELREHBER.Entitiy.Oteliletisim", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("OtelID")
                        .HasColumnType("bigint");

                    b.Property<string>("Telefon_Numarası")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OtelID");

                    b.ToTable("Oteliletisims");
                });

            modelBuilder.Entity("OTELREHBER.Entitiy.Oteliletisim", b =>
                {
                    b.HasOne("OTELREHBER.Entitiy.Otel", "Otel")
                        .WithMany("OteliletIsimList")
                        .HasForeignKey("OtelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Otel");
                });

            modelBuilder.Entity("OTELREHBER.Entitiy.Otel", b =>
                {
                    b.Navigation("OteliletIsimList");
                });
#pragma warning restore 612, 618
        }
    }
}
